[package]
name = "sarkara-capi"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
build = "build.rs"

[lib]
name = "sarkara"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
sarkara = "*"

[build-dependencies]
rusty-cheddar = "*"
